### ISSUE TITLE
Fails to load

### ISSUE THREAD

**Issue by abdcef** [bramses/summarize-with-gpt3-obsidian#1]
The plugin fails to load after installing. Can you make it BRAT compatible?

**Comment by janpeeters70** [comment]
I  just came here to ask for BRAT functionality. Thanks for considering.

**Comment by bramses** [comment]
Thanks for reaching out, all. I'll try and get this on BART by end of December

**Comment by paraalan** [comment]
I was wondering if there is a work-around to the plugin to load? I've not seen the Failed to load plugin message before and haven't been able to find a reference for how to troubleshoot. I'd love to try this plugin!

**Comment by amarks** [comment]
I am wondering if there is a work-around for the issue in the meantime? I haven't seen this error before and can't locate any troubleshooting steps. Love to try the plugin!

**Comment by dxcore35** [comment]
Same problem cannot open the plugin. Please BRAT!

**Comment by ChrisSwan** [comment]
Same "failed to load plugin" error when I try to enable it. I'm using windows if that helps.

**Comment by Derivedbetter** [comment]
Any luck on this? Having the same issues. Tried many workarounds. No joy. Seems like a great concept though.

**Comment by bramses** [comment]
Thank you all for waiting -- should be up on BRAT now, just published a release: https://github.com/bramses/summarize-with-gpt3-obsidian/releases/tag/1.0.1
