### ISSUE TITLE
Update to GPT 4?

### ISSUE THREAD

**Issue by sm18lr88** [bramses/summarize-with-gpt3-obsidian#4]
For those of us who subscribed for GPT 4, is there a way to use this model vs GPT 3?

**Comment by bramses** [comment]
i havent edited this codebase in a while, but your best bet is to install it locally and add the gpt-4 engine to this line: 					https://github.com/bramses/summarize-with-gpt3-obsidian/blob/e59c737df51de1546e040a2a8d1419df9092b4aa/main.ts#L221

**Comment by sm18lr88** [comment]
I had GPT 4 help me out. Here is the solution (at least it seems to work for me). Sorry I'm not submitting it in some official way. I'm not a programmer and don't really know how to use Github:

In Main.ts:
```ts
const DEFAULT_SETTINGS: GPT3SummarizerSettings = {
	apiKey: "default",
	engine: "gpt-4", // Change this line
	tagToggle: true,
	keepOriginal: true,
};

And further down:

// dropdown setting for choosing engine
new Setting(containerEl)
	.setName("Engine")
	.setDesc("Choose the engine to use for summarization")
	.addDropdown((dropdown) =>
		dropdown
			.addOption("gpt-4", "GPT-4") // Add this line for GPT-4
			.addOption("text-davinci-003", "Davinci")
			.addOption("text-curie-001", "Curie")
			.addOption("text-babbage-001", "Babbage")
			.addOption("text-ada-001", "Ada")
```


In Main.js, line ~162, we add the option also GPT-4 in the drop-down menu:

```
...
new import_obsidian.Setting(containerEl).setName("Engine").setDesc("Choose the engine to use for summarization").addDropdown((dropdown) => dropdown.addOption("text-davinci-003", "Davinci").addOption("text-curie-001", "Curie").addOption("text-babbage-001", "Babbage").addOption("text-ada-001", "Ada").addOption("gpt-4", "GPT-4").setValue(this.plugin.settings.engine).onChange((value) => __async(this, null, function* () {
...
```

**Comment by bramses** [comment]
So upon further research, the [completions endpoint doesn't support GPT-4](https://platform.openai.com/docs/models/model-endpoint-compatibility) and you'd have to move to the [ChatML format](https://platform.openai.com/docs/guides/chat/introduction).

You would need to do light surgery on [this method](https://github.com/bramses/summarize-with-gpt3-obsidian/blob/master/main.ts#L32-L57) to make it conform to the new ChatML format, see [this plugin as an example](https://github.com/bramses/chatgpt-md/blob/master/main.ts#L115-L160)

> In Main.js, line ~162, we add the option also GPT-4 in the drop-down menu:

You shouldn't edit `main.js` directly, instead use `npm run build`!
